### ISSUE TITLE
error creando la pagina de ofertas recientes

### ISSUE THREAD

**Issue by byk3v** [javiereguiluz/Cupon#111]
Hola Javier, ante nada gracias por esta iniciativa

He llegado al capitulo 7.6  y al crear la ruta para las ofertas recientes como se indica en el libro:

``` yaml
ciudad_recientes:
    pattern: /{ciudad}/recientes
    defaults: { _controller: CiudadBundle:Default:recientes }
```

el navegador me lanza 

```
FileLoaderLoadException Cannot import resource "var/www/grupon/src/Cupon/CiudadBundle/Resources/config/routing.yml" from "var/www/grupon/app/config/routing.yml"
```

De lo que entendi dice algo como  que el argumento 1 que se le pasa debe ser un array y le esta llegando null.

como se indica en el libro cree la accion en el controlador, y solo me da el error cuando creo la ruta.  Espero puedan ayudarme

Saludos
