### ISSUE TITLE
Traduciendo contenidos dinámicos, error o falta informaicón

### ISSUE THREAD

**Issue by santo76** [javiereguiluz/Cupon#122]
Hola,
estoy aprendiendo Symfony2 junto con la aplicación Cupon. Antes que nada agradecer el hecho de haber desarrollado esta aplicación mas el libro guía del mismo, a mi me este sirviendo mucho para iniciarme.

Me encuentro con el problema de que estoy en el punto de implementar la traducción multiidioma en tablas y me da el siguiente error cuando hago el flush() de la entidad con multiidioma.
(The class 'Gedmo\Translatable\Entity\Translation' was not found in the chain configured namespaces Cupon\OfertaBundle\Entity).

Como estoy programando desde 0, me he bajado la versión del cupon 2.3 para comprobar si he hecho algo mal y veo que en el libro se habla de instalar un Bundle adicional añadiendo la siguiente linea al composer.json "stof/doctrine-extensions-bundle": "dev-master". Dicha linea, no la he visto en el cupon que me he descargado desde github, así como tampoco veo ninguna referencia en las entidades (de ofertas por ejemplo), entonces no se si este apartado esta incompleto o no esta probado todavía.

Por favor, me podría indicar si alguien ha llegado a este punto y se encuentra con el mismo problema que yo y si es así que solución a utilizado?

Muchas gracias.

**Comment by kerunaru** [comment]
Quizás es un poco tarde pero yo lo he solucionado poniendo estas líneas en mi `/app/config/config.yml` dentro de `doctrine.orm.mappings`:

```yml
gedmo_translatable:
  type: annotation
  prefix: Gedmo\Translatable\Entity
  dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
  alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
  is_bundle: false
gedmo_loggable:
  type: annotation
  prefix: Gedmo\Loggable\Entity
  dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
  alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
  is_bundle: false
```

Se explica [aquí](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html)
